<a href="https://colab.research.google.com/github/yogeshsinghgit/Pwskills_Assignment/blob/main/Numpy_Basics_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics Assignment

[Assignment Link](https://drive.google.com/file/d/1te1qkBrWcohVW95SHXAU7bks9f2zQZQK/view)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.



```Python
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
```



In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


The list_ is a sequence of type list whereas the array_list is an numpy array of some characters.

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
for i, j in zip(list_, array_list):
  print(f"{i} in list_ is {type(i)} and {j} in array_list is {type(j)}")

1 in list_ is <class 'str'> and 1 in array_list is <class 'numpy.str_'>
2 in list_ is <class 'str'> and 2 in array_list is <class 'numpy.str_'>
3 in list_ is <class 'str'> and 3 in array_list is <class 'numpy.str_'>
4 in list_ is <class 'str'> and 4 in array_list is <class 'numpy.str_'>
5 in list_ is <class 'str'> and 5 in array_list is <class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:

`array_list = np.array(object = list_, dtype = int)`

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.





In [5]:
array_list = np.array(object = list_, dtype = int)
for i, j in zip(list_, array_list):
  print(f"{i} in list_ is {type(i)} and {j} in array_list is {type(j)}")

1 in list_ is <class 'str'> and 1 in array_list is <class 'numpy.int64'>
2 in list_ is <class 'str'> and 2 in array_list is <class 'numpy.int64'>
3 in list_ is <class 'str'> and 3 in array_list is <class 'numpy.int64'>
4 in list_ is <class 'str'> and 4 in array_list is <class 'numpy.int64'>
5 in list_ is <class 'str'> and 5 in array_list is <class 'numpy.int64'>


The answer is YES, That there will be some difference between the datatype of each iterable elements.

as we can see the datatype of each element of array_list which is a numpy array is converted to int class, whereas the list element datatype remain same.

Consider the below code to answer further questions:



```Python
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

## Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [8]:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(f"The Shape of num_list = {num_array.shape}")
print(f"The Size of num_list = {num_array.size}")

The Shape of num_list = (2, 3)
The Size of num_list = 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

> [Hint: The size of the array will be 9 and the shape will be (3,3).]



In [9]:
import numpy as np

# Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))

# Print the array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?

> [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]



np.eye(5) is the function that efficiently constructs the identity matrix. It takes a single argument, which is the desired dimension of the matrix (both rows and columns).

The output from np.eye(5) is stored in the variable identity_matrix.

In [10]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
